' ========================
' 内容管理上下文
' ========================
package "Content Management" {
  class Content <<AggregateRoot>> {
    - contentId: String
    - type: ContentType
    - author: UserId
    - createTime: DateTime
    - updateTime: DateTime
    - content: clob
    + publish()
    + delete()
    + update()
  }

  enum ContentType {
    TECH_DOC
    LEGAL_DOC
    BLOG
    PROJECT_REPORT
  }
}